### ISSUE TITLE
Export CSV button on inventory doesn't actually export & provides JSON results

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#87]
When using the **Export to CSV** button located at the bottom of inventory, when the results are returned, they are not provided in the form of a CSV file and the results that are provided are given in a separate webpage in JSON format.

<img width="1652" alt="screen shot 2017-05-11 at 2 19 00 pm" src="https://cloud.githubusercontent.com/assets/343792/25965099/fcf0ffbc-3654-11e7-98be-255437f43d0f.png">

**Comment by jharting** [comment]
Fixed in beta and stable

**Comment by Robcwilliams** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1450764

**Comment by Robcwilliams** [comment]
@jharting confirmed all set in beta, stable still appears to be producing JSON
